### ISSUE TITLE
request latencies  are zero for upstream

### ISSUE THREAD

**Issue by pzhuk** [Nebo15/annon.api#269]
We are running annon as a gateway for eHealth UA project, and what I see, is that upstream latenecy always zero . 
Any hints on this metric?

Tnx

**Comment by AndrewDryga** [comment]
Hi,

Where do you check the latency? Via annonktl or in web UI? What is the annon's version that you using?

**Comment by pzhuk** [comment]
I'm checking a latency records in the gateway db, table requests
We are running container
edenlabllc/annon_api:0.12.4
docker://sha256:c3cdd59821b36c3b839c9e3ee595db92912dcd9c703e05eaba7bc51a92ed5ea7

**Comment by AndrewDryga** [comment]
@pzhuk Annon doesn't have that version - https://github.com/Nebo15/annon.api/releases. You are using forked one. To tell what is going wrong there we need an investigation of what was changed in that fork..

Generally speaking, It is possible to have 0 upstream latency when the request was dispatched from Annon, eg. when you have validator plug and no request to the upstream API was made.

Other options to look for a bug:
- Logger plugin is not called to persist latencies (then all numbers would be 0-ed);
- The custom Proxy adapter doesn't assign upstream latency to the connection.

**Comment by pzhuk** [comment]
Thanks for clarification @AndrewDryga
